"""Initial Hush schema.

Creates all 21 tables: identity, guild configuration, confessions and
engagement, moderation, notifications, drafts and audit records.

Original message: initial schema

Revision ID: fecad2bbf464
Revises: 
Create Date: 2026-09-05 22:57:32.988418
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('requested_by_discord_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('scope', sa.Enum('FULL', 'GUILD', 'USER', 'ALIAS', 'CONFESSION', 'MODERATION', 'CONFESSIONS_ONLY', 'REPORTS_ONLY', name='exportscope', native_enum=False, length=40), nullable=False),
    sa.Column('export_format', sa.Enum('JSON', 'CSV', 'TXT', 'ZIP', name='exportformat', native_enum=False, length=40), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('target', sa.String(length=120), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('row_counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports'))
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index('ix_export_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exports_requested_by_discord_id'), ['requested_by_discord_id'], unique=False)

    op.create_table('guilds',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guilds'))
    )
    with op.batch_alter_table('guilds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guilds_created_at'), ['created_at'], unique=False)

    op.create_table('moderation_ledger',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.Enum('RULES_ACCEPTED', 'RULES_REACCEPTED', 'CONFESSION_CREATED', 'CONFESSION_REMOVED', 'WARNING_CREATED', 'WARNING_ACKNOWLEDGED', 'WARNING_REVOKED', 'TEMP_BAN_CREATED', 'TEMP_BAN_EXPIRED', 'PERMANENT_BAN_CREATED', 'BAN_REVOKED', 'ALIAS_CREATED', 'ALIAS_ROTATED', 'REPORT_CREATED', 'REPORT_RESOLVED', 'EXPORT_CREATED', 'IDENTITY_LOOKUP', 'CONFIG_CHANGED', name='ledgeraction', native_enum=False, length=40), nullable=False),
    sa.Column('internal_user_id', sa.String(length=64), nullable=True),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('moderator_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('confession_id', sa.String(length=64), nullable=True),
    sa.Column('alias_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('previous_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('new_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_ledger'))
    )
    with op.batch_alter_table('moderation_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_action', ['action_type'], unique=False)
        batch_op.create_index('ix_ledger_guild_created', ['guild_id', 'created_at'], unique=False)
        batch_op.create_index('ix_ledger_user', ['internal_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_ledger_created_at'), ['created_at'], unique=False)

    op.create_table('system_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index('ix_system_event_type_created', ['event_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('is_globally_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_discord_user_id'), ['discord_user_id'], unique=True)

    op.create_table('agreements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('agreement_version', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_agreements_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.id'], name=op.f('fk_agreements_internal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agreements')),
    sa.UniqueConstraint('internal_user_id', 'guild_id', 'agreement_version', name='uq_agreement_user_guild_version')
    )
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.create_index('ix_agreement_lookup', ['internal_user_id', 'guild_id'], unique=False)

    op.create_table('anon_aliases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_alias', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotation_reason', sa.String(length=200), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_anon_aliases_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.id'], name=op.f('fk_anon_aliases_internal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anon_aliases')),
    sa.UniqueConstraint('guild_id', 'public_alias', name='uq_alias_guild_public')
    )
    with op.batch_alter_table('anon_aliases', schema=None) as batch_op:
        batch_op.create_index('ix_alias_user_guild', ['internal_user_id', 'guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anon_aliases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_anon_aliases_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_anon_aliases_public_alias'), ['public_alias'], unique=False)
        batch_op.create_index('uq_alias_current_per_user', ['internal_user_id', 'guild_id'], unique=True, sqlite_where=sa.text('is_current = 1'), postgresql_where=sa.text('is_current = true'))

    op.create_table('bans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('moderator_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_bans_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.id'], name=op.f('fk_bans_internal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bans'))
    )
    with op.batch_alter_table('bans', schema=None) as batch_op:
        batch_op.create_index('ix_ban_user_guild_active', ['internal_user_id', 'guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bans_created_at'), ['created_at'], unique=False)

    op.create_table('guild_memberships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_guild_memberships_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.id'], name=op.f('fk_guild_memberships_internal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild_memberships')),
    sa.UniqueConstraint('internal_user_id', 'guild_id', name='uq_membership_user_guild')
    )
    with op.batch_alter_table('guild_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guild_memberships_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_memberships_internal_user_id'), ['internal_user_id'], unique=False)
        batch_op.create_index('ix_membership_guild', ['guild_id'], unique=False)

    op.create_table('guild_settings',
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('confession_channel_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('mod_log_channel_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('moderator_role_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('rules_version', sa.Integer(), nullable=False),
    sa.Column('ratings_enabled', sa.Boolean(), nullable=False),
    sa.Column('followers_enabled', sa.Boolean(), nullable=False),
    sa.Column('bookmarks_enabled', sa.Boolean(), nullable=False),
    sa.Column('polls_enabled', sa.Boolean(), nullable=False),
    sa.Column('updates_enabled', sa.Boolean(), nullable=False),
    sa.Column('trending_enabled', sa.Boolean(), nullable=False),
    sa.Column('confession_character_limit', sa.Integer(), nullable=False),
    sa.Column('alias_rotation_days', sa.Integer(), nullable=False),
    sa.Column('minimum_account_age_days', sa.Integer(), nullable=False),
    sa.Column('rating_scale_max', sa.Integer(), nullable=False),
    sa.Column('require_warning_acknowledgement', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_guild_settings_guild_id_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_guild_settings'))
    )
    with op.batch_alter_table('guild_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guild_settings_created_at'), ['created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('kind', sa.Enum('WARNING', 'BAN', 'BAN_REVOKED', 'CONFESSION_REMOVED', 'FOLLOW_NEW_CONFESSION', name='notificationkind', native_enum=False, length=40), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', name='notificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('requires_acknowledgement', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.id'], name=op.f('fk_notifications_internal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_pending', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_notification_user_blocking', ['internal_user_id', 'guild_id', 'is_blocking'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    op.create_table('confessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('public_number', sa.Integer(), nullable=False),
    sa.Column('internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('alias_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'FAILED', 'REMOVED', name='confessionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('discord_message_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('discord_channel_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('parent_confession_id', sa.String(length=64), nullable=True),
    sa.Column('root_confession_id', sa.String(length=64), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('delete_reason', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alias_id'], ['anon_aliases.id'], name=op.f('fk_confessions_alias_id_anon_aliases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_confessions_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.id'], name=op.f('fk_confessions_internal_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_confession_id'], ['confessions.id'], name=op.f('fk_confessions_parent_confession_id_confessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confessions')),
    sa.UniqueConstraint('guild_id', 'public_number', name='uq_confession_guild_number'),
    sa.UniqueConstraint('idempotency_key', name='uq_confession_idempotency')
    )
    with op.batch_alter_table('confessions', schema=None) as batch_op:
        batch_op.create_index('ix_confession_alias', ['alias_id'], unique=False)
        batch_op.create_index('ix_confession_guild_created', ['guild_id', 'created_at'], unique=False)
        batch_op.create_index('ix_confession_guild_status', ['guild_id', 'status'], unique=False)
        batch_op.create_index('ix_confession_root', ['root_confession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confessions_content_fingerprint'), ['content_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_confessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_confessions_discord_message_id'), ['discord_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confessions_internal_user_id'), ['internal_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confessions_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('follows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('follower_internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('alias_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alias_id'], ['anon_aliases.id'], name=op.f('fk_follows_alias_id_anon_aliases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_internal_user_id'], ['users.id'], name=op.f('fk_follows_follower_internal_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_follows_guild_id_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follows')),
    sa.UniqueConstraint('follower_internal_user_id', 'alias_id', name='uq_follow_follower_alias')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('ix_follow_alias', ['alias_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_follower_internal_user_id'), ['follower_internal_user_id'], unique=False)

    op.create_table('bookmarks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('confession_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confession_id'], ['confessions.id'], name=op.f('fk_bookmarks_confession_id_confessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.id'], name=op.f('fk_bookmarks_internal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmarks')),
    sa.UniqueConstraint('internal_user_id', 'confession_id', name='uq_bookmark_user_confession')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index('ix_bookmark_user', ['internal_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_confession_id'), ['confession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_created_at'), ['created_at'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_confession_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_drafts_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.id'], name=op.f('fk_drafts_internal_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_confession_id'], ['confessions.id'], name=op.f('fk_drafts_parent_confession_id_confessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drafts')),
    sa.UniqueConstraint('internal_user_id', 'guild_id', name='uq_draft_user_guild')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index('ix_draft_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_created_at'), ['created_at'], unique=False)

    op.create_table('polls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('confession_id', sa.String(length=64), nullable=False),
    sa.Column('created_by_internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confession_id'], ['confessions.id'], name=op.f('fk_polls_confession_id_confessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_internal_user_id'], ['users.id'], name=op.f('fk_polls_created_by_internal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polls')),
    sa.UniqueConstraint('confession_id', name='uq_poll_confession')
    )
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_polls_created_at'), ['created_at'], unique=False)

    op.create_table('ratings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('confession_id', sa.String(length=64), nullable=False),
    sa.Column('voter_internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confession_id'], ['confessions.id'], name=op.f('fk_ratings_confession_id_confessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_internal_user_id'], ['users.id'], name=op.f('fk_ratings_voter_internal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('confession_id', 'voter_internal_user_id', name='uq_rating_confession_voter')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index('ix_rating_confession', ['confession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_created_at'), ['created_at'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('confession_id', sa.String(length=64), nullable=False),
    sa.Column('reporter_internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.Enum('SELF_HARM', 'SEXUAL_ASSAULT', 'MINOR_SEXUAL_CONTENT', 'THREATS', 'DOXXING', 'HARASSMENT', 'GRAPHIC', 'OTHER', name='reportreason', native_enum=False, length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='reportstatus', native_enum=False, length=40), nullable=False),
    sa.Column('resolved_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confession_id'], ['confessions.id'], name=op.f('fk_reports_confession_id_confessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_reports_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_internal_user_id'], ['users.id'], name=op.f('fk_reports_reporter_internal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('confession_id', 'reporter_internal_user_id', name='uq_report_confession_reporter')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_report_guild_status', ['guild_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_confession_id'), ['confession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)

    op.create_table('warnings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('moderator_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('related_confession_id', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_warnings_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.id'], name=op.f('fk_warnings_internal_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_confession_id'], ['confessions.id'], name=op.f('fk_warnings_related_confession_id_confessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warnings'))
    )
    with op.batch_alter_table('warnings', schema=None) as batch_op:
        batch_op.create_index('ix_warning_user_guild', ['internal_user_id', 'guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warnings_created_at'), ['created_at'], unique=False)

    op.create_table('poll_options',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('poll_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_poll_options_poll_id_polls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poll_options')),
    sa.UniqueConstraint('poll_id', 'position', name='uq_poll_option_position')
    )
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_options_poll_id'), ['poll_id'], unique=False)

    op.create_table('poll_votes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('poll_id', sa.String(length=64), nullable=False),
    sa.Column('option_id', sa.String(length=64), nullable=False),
    sa.Column('voter_internal_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], name=op.f('fk_poll_votes_option_id_poll_options'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_poll_votes_poll_id_polls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_internal_user_id'], ['users.id'], name=op.f('fk_poll_votes_voter_internal_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poll_votes')),
    sa.UniqueConstraint('poll_id', 'voter_internal_user_id', name='uq_poll_vote_voter')
    )
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.create_index('ix_poll_vote_option', ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_votes_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_votes_created_at'))
        batch_op.drop_index('ix_poll_vote_option')

    op.drop_table('poll_votes')
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_options_poll_id'))

    op.drop_table('poll_options')
    with op.batch_alter_table('warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warnings_created_at'))
        batch_op.drop_index('ix_warning_user_guild')

    op.drop_table('warnings')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_reports_confession_id'))
        batch_op.drop_index('ix_report_guild_status')

    op.drop_table('reports')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_created_at'))
        batch_op.drop_index('ix_rating_confession')

    op.drop_table('ratings')
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_polls_created_at'))

    op.drop_table('polls')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_created_at'))
        batch_op.drop_index('ix_draft_expires')

    op.drop_table('drafts')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_created_at'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_confession_id'))
        batch_op.drop_index('ix_bookmark_user')

    op.drop_table('bookmarks')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_follower_internal_user_id'))
        batch_op.drop_index(batch_op.f('ix_follows_created_at'))
        batch_op.drop_index('ix_follow_alias')

    op.drop_table('follows')
    with op.batch_alter_table('confessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confessions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_confessions_internal_user_id'))
        batch_op.drop_index(batch_op.f('ix_confessions_discord_message_id'))
        batch_op.drop_index(batch_op.f('ix_confessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_confessions_content_fingerprint'))
        batch_op.drop_index('ix_confession_root')
        batch_op.drop_index('ix_confession_guild_status')
        batch_op.drop_index('ix_confession_guild_created')
        batch_op.drop_index('ix_confession_alias')

    op.drop_table('confessions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index('ix_notification_user_blocking')
        batch_op.drop_index('ix_notification_pending')

    op.drop_table('notifications')
    with op.batch_alter_table('guild_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_settings_created_at'))

    op.drop_table('guild_settings')
    with op.batch_alter_table('guild_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_membership_guild')
        batch_op.drop_index(batch_op.f('ix_guild_memberships_internal_user_id'))
        batch_op.drop_index(batch_op.f('ix_guild_memberships_created_at'))

    op.drop_table('guild_memberships')
    with op.batch_alter_table('bans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bans_created_at'))
        batch_op.drop_index('ix_ban_user_guild_active')

    op.drop_table('bans')
    with op.batch_alter_table('anon_aliases', schema=None) as batch_op:
        batch_op.drop_index('uq_alias_current_per_user', sqlite_where=sa.text('is_current = 1'), postgresql_where=sa.text('is_current = true'))
        batch_op.drop_index(batch_op.f('ix_anon_aliases_public_alias'))
        batch_op.drop_index(batch_op.f('ix_anon_aliases_is_current'))
        batch_op.drop_index(batch_op.f('ix_anon_aliases_created_at'))
        batch_op.drop_index('ix_alias_user_guild')

    op.drop_table('anon_aliases')
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_index('ix_agreement_lookup')

    op.drop_table('agreements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_discord_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_events_created_at'))
        batch_op.drop_index('ix_system_event_type_created')

    op.drop_table('system_events')
    with op.batch_alter_table('moderation_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_ledger_created_at'))
        batch_op.drop_index('ix_ledger_user')
        batch_op.drop_index('ix_ledger_guild_created')
        batch_op.drop_index('ix_ledger_action')

    op.drop_table('moderation_ledger')
    with op.batch_alter_table('guilds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guilds_created_at'))

    op.drop_table('guilds')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_requested_by_discord_id'))
        batch_op.drop_index(batch_op.f('ix_exports_created_at'))
        batch_op.drop_index('ix_export_expires')

    op.drop_table('exports')
    # ### end Alembic commands ###
