"""Per-guild Hush admin and moderator roles.

Adds the columns that let a server owner delegate Hush management without
granting Discord Administrator. Existing rows default to empty lists, so
behaviour is unchanged until an owner configures something.

Original message: hush admin and moderator roles

Revision ID: ec0b72d5b5fc
Revises: 0001_initial_schema
Create Date: 2026-09-05 23:34:52.060615
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '0002_hush_roles'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_role_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('admin_user_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('moderator_user_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_settings', schema=None) as batch_op:
        batch_op.drop_column('moderator_user_ids')
        batch_op.drop_column('admin_user_ids')
        batch_op.drop_column('admin_role_ids')

    # ### end Alembic commands ###
